name: CI Test

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Ci Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request_head.sha }}
      - name: Linter Check
        run: |
          npm i -g pnpm@9.1.0
          pnpm i
          pnpm lint
      - name: ESLint Tests
        run: |
          pnpm build
          pnpm test
          pnpm test:flat
          pnpm test:esm
